[package]
name = "tadeuszhs/catvert"
description = "Library for converting between CatWeb's JSON structure and Roblox instances."
license = "BSD-3-Clause"
authors = ["TadeuszHS"]
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["resources", "plugin", "tests", "test.project.json"]
private = true

[dev-dependencies]
vide = "centau/vide@0.4.1"
