--!strict

--[=[
	Indexer of CatWeb Enums with their value being their corresponding Roblox equivalent.
]=]
return table.freeze({
	ApplyStrokeMode = Enum.ApplyStrokeMode,
	BorderStrokePosition = Enum.BorderStrokePosition,
	FillDirection = Enum.FillDirection,
	Font = Enum.Font,
	FontStyle = Enum.FontStyle,
	FontWeight = Enum.FontWeight,
	HorizontalAlignment = Enum.HorizontalAlignment,
	LineJoinMode = Enum.LineJoinMode,
	ResamplerMode = Enum.ResamplerMode,
	ScaleType = Enum.ScaleType,
	SortOrder = Enum.SortOrder,
	StrokeSizingMode = Enum.StrokeSizingMode,
	TextTruncate = Enum.TextTruncate,
	TextXAlignment = Enum.TextXAlignment,
	TextYAlignment = Enum.TextYAlignment,
	VerticalAlignment = Enum.VerticalAlignment,
	UIFlexMode = Enum.UIFlexMode,
	ItemLineAlignment = Enum.ItemLineAlignment,
})
